apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-k8s.fullname" . }}
  labels:
    {{- include "nodejs-k8s.labels" . | nindent 4 }}
data:
  DB_HOST: '{{ .Values.environment.db_host }}'
  DB_USER: '{{ .Values.environment.db_user }}'
  DB_NAME: '{{ .Values.environment.db_name }}'
