apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-k8s.fullname" . }}
  labels:
    {{- include "nodejs-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: '{{ .Values.environment.db_password }}'
